// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGb_ylOqmWPP9fHtof2umGJaMJtNJxEc',
    appId: '1:635030450307:web:d5a6fbba929a3e5e006bb6',
    messagingSenderId: '635030450307',
    projectId: 'chatapp-28072',
    authDomain: 'chatapp-28072.firebaseapp.com',
    storageBucket: 'chatapp-28072.appspot.com',
    measurementId: 'G-4N6QBBBWHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0esMRn3HzGRf-eYRYiZoR6Lz39ZD8U0',
    appId: '1:635030450307:android:81843923abe8d3ce006bb6',
    messagingSenderId: '635030450307',
    projectId: 'chatapp-28072',
    storageBucket: 'chatapp-28072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXNMIcMQivGxkS8kAqQVw9DNcWvcYHD8',
    appId: '1:635030450307:ios:394459cdac5b27bf006bb6',
    messagingSenderId: '635030450307',
    projectId: 'chatapp-28072',
    storageBucket: 'chatapp-28072.appspot.com',
    iosClientId: '635030450307-0frilnea4hk05v5tgpgianob27taec20.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
